---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

platform:
  os: linux
  arch: arm64


node:
  cloud: oracle
  location: tokyo

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: gomodcache
    host:
      path: /var/docker/drone-runner/cache/gomod

steps:

  # Multi-platform build using built-in buildx
  # @see: https://docs.drone.io/pipeline/docker/examples/services/docker/
  - name: build-docker
    image: docker:dind
    when:
      event:
        - tag
    environment:
      password:
        from_secret: registry-password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      - docker login --username=cloverzrg -p $password
      - docker buildx create --use
      - docker buildx build --platform linux/arm64,linux/amd64,linux/386,linux/arm -t cloverzrg/go-shadowsocks2:$DRONE_TAG -t cloverzrg/go-shadowsocks2:latest --push --build-arg DRONE_TAG=$DRONE_TAG .

  - name: build-docker-latest
    image: docker:dind
    when:
      branch:
        - master
    environment:
      password:
        from_secret: registry-password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      - docker login --username=cloverzrg -p $password
      - docker buildx create --use
      - docker buildx build --platform linux/arm64,linux/amd64,linux/386 -t cloverzrg/go-shadowsocks2:latest --push --build-arg DRONE_TAG=master .
